/**
 * Paint palettes for Colour Mixer.
 * Brand hex values are approximate mass-tones for planning — not manufacturer spectral data.
 */
window.PAINT_PALETTES = {
  limited: [
    {
      id: "hansa-y",
      name: "Hansa Yellow (cool)",
      hex: "#F5D031",
      family: "yellow",
      note: "Cool yellow — clean greens with phthalo",
    },
    {
      id: "cad-y",
      name: "Cadmium Yellow (warm)",
      hex: "#F2B705",
      family: "yellow",
      note: "Warm yellow — oranges with warm red",
    },
    {
      id: "pyrrole-r",
      name: "Pyrrole Red (warm)",
      hex: "#E23C28",
      family: "red",
      note: "Warm red — lively oranges",
    },
    {
      id: "quin-rose",
      name: "Quinacridone Rose (cool)",
      hex: "#C4356A",
      family: "red",
      note: "Cool red/magenta — clean purples",
    },
    {
      id: "ultra-b",
      name: "Ultramarine Blue (warm)",
      hex: "#2B4C9B",
      family: "blue",
      note: "Warm blue — violets with rose",
    },
    {
      id: "phthalo-b",
      name: "Phthalo Blue (cool)",
      hex: "#0A4D8C",
      family: "blue",
      note: "Cool blue — strong tinting; use sparingly",
    },
    {
      id: "burnt-s",
      name: "Burnt Sienna",
      hex: "#8A3B1E",
      family: "earth",
      note: "Warm earth — neutrals with ultramarine",
    },
    {
      id: "yellow-o",
      name: "Yellow Ochre",
      hex: "#C9953B",
      family: "earth",
      note: "Muted yellow earth",
    },
    {
      id: "paynes",
      name: "Payne's Grey",
      hex: "#3D4A5C",
      family: "neutral",
      note: "Cool dark — softer than black",
    },
  ],

  /** Generic common names (not brand-specific) */
  named: [
    { id: "lemon-y", name: "Lemon Yellow", hex: "#F4E04D", brandish: "common", family: "yellow" },
    { id: "cad-y-deep", name: "Cadmium Yellow Deep", hex: "#E8A317", brandish: "common", family: "yellow" },
    { id: "indian-y", name: "Indian Yellow", hex: "#E3A018", brandish: "common", family: "yellow" },
    { id: "cad-o", name: "Cadmium Orange", hex: "#E86A17", brandish: "common", family: "orange" },
    { id: "cad-r", name: "Cadmium Red Medium", hex: "#D4322C", brandish: "common", family: "red" },
    { id: "alizarin", name: "Alizarin Crimson", hex: "#9B1B30", brandish: "common", family: "red" },
    { id: "quin-mag", name: "Quinacridone Magenta", hex: "#A61C5C", brandish: "common", family: "red" },
    { id: "perm-rose", name: "Permanent Rose", hex: "#D94F7C", brandish: "common", family: "red" },
    { id: "diox-p", name: "Dioxazine Purple", hex: "#4A2C6A", brandish: "common", family: "violet" },
    { id: "cobalt-v", name: "Cobalt Violet", hex: "#8B5A9E", brandish: "common", family: "violet" },
    { id: "cobalt-b", name: "Cobalt Blue", hex: "#2F5FA8", brandish: "common", family: "blue" },
    { id: "cerulean", name: "Cerulean Blue", hex: "#2A7EB5", brandish: "common", family: "blue" },
    { id: "prussian", name: "Prussian Blue", hex: "#0B2E4A", brandish: "common", family: "blue" },
    { id: "indanthrene", name: "Indanthrene Blue", hex: "#1E3A6E", brandish: "common", family: "blue" },
    { id: "phthalo-g", name: "Phthalo Green", hex: "#0B6B4F", brandish: "common", family: "green" },
    { id: "sap-g", name: "Sap Green", hex: "#4F7A2E", brandish: "common", family: "green" },
    { id: "viridian", name: "Viridian", hex: "#2E7A66", brandish: "common", family: "green" },
    { id: "hookers", name: "Hooker's Green", hex: "#3A6B3A", brandish: "common", family: "green" },
    { id: "raw-sienna", name: "Raw Sienna", hex: "#B8833B", brandish: "common", family: "earth" },
    { id: "raw-umber", name: "Raw Umber", hex: "#6B4E31", brandish: "common", family: "earth" },
    { id: "burnt-umber", name: "Burnt Umber", hex: "#5C3317", brandish: "common", family: "earth" },
    { id: "venetian", name: "Venetian Red", hex: "#A33B2B", brandish: "common", family: "earth" },
    { id: "titanium-w", name: "Titanium White", hex: "#F7F5F0", brandish: "acrylic", family: "neutral", acrylicOnly: true },
    { id: "zinc-w", name: "Zinc White", hex: "#F2F0EA", brandish: "acrylic", family: "neutral", acrylicOnly: true },
    { id: "ivory-blk", name: "Ivory Black", hex: "#1A1A1A", brandish: "common", family: "neutral" },
    { id: "lamp-blk", name: "Lamp Black", hex: "#0D0D0D", brandish: "acrylic", family: "neutral" },
    { id: "neutral-tint", name: "Neutral Tint", hex: "#2C2C34", brandish: "common", family: "neutral" },
  ],
};

/**
 * Popular brand lines. Hex ≈ mass-tone for planning only.
 * medium: "watercolour" | "acrylic" | "both"
 */
window.BRAND_PALETTES = [
  {
    id: "wn-pwc",
    brand: "Winsor & Newton",
    line: "Professional Watercolour",
    medium: "watercolour",
    note: "Core studio colours from the Professional range.",
    paints: [
      { name: "Winsor Lemon", hex: "#F4E84A", pigment: "PY175" },
      { name: "Bismuth Yellow", hex: "#F5E055", pigment: "PY184" },
      { name: "Cadmium Yellow Pale", hex: "#F7D23A", pigment: "PY35" },
      { name: "Winsor Yellow", hex: "#F2C41A", pigment: "PY154" },
      { name: "Cadmium Yellow", hex: "#F0B400", pigment: "PY35" },
      { name: "Indian Yellow", hex: "#E39A18", pigment: "PY153" },
      { name: "Cadmium Orange", hex: "#E86A1A", pigment: "PO20" },
      { name: "Winsor Orange", hex: "#E85A20", pigment: "PO73" },
      { name: "Winsor Red", hex: "#D92B2B", pigment: "PR254" },
      { name: "Cadmium Red", hex: "#D42B24", pigment: "PR108" },
      { name: "Scarlet Lake", hex: "#D93A2E", pigment: "PR188" },
      { name: "Permanent Alizarin Crimson", hex: "#8E1C36", pigment: "PR206" },
      { name: "Permanent Rose", hex: "#D24A7C", pigment: "PV19" },
      { name: "Quinacridone Magenta", hex: "#A61C5C", pigment: "PR122" },
      { name: "Permanent Magenta", hex: "#8B2A5B", pigment: "PV19" },
      { name: "Winsor Violet (Dioxazine)", hex: "#4A2A6B", pigment: "PV23" },
      { name: "French Ultramarine", hex: "#2E4A9B", pigment: "PB29" },
      { name: "Ultramarine (Green Shade)", hex: "#2A4A8C", pigment: "PB29" },
      { name: "Cobalt Blue", hex: "#2F5FA8", pigment: "PB28" },
      { name: "Cerulean Blue", hex: "#2A7EB5", pigment: "PB35" },
      { name: "Winsor Blue (Green Shade)", hex: "#005A8C", pigment: "PB15" },
      { name: "Winsor Blue (Red Shade)", hex: "#0A3D7A", pigment: "PB15:1" },
      { name: "Indigo", hex: "#1A2E4A", pigment: "PB15/PBk6/PV19" },
      { name: "Winsor Green (Yellow Shade)", hex: "#0A7A4A", pigment: "PG36" },
      { name: "Winsor Green (Blue Shade)", hex: "#006B5A", pigment: "PG7" },
      { name: "Permanent Sap Green", hex: "#3F6B2E", pigment: "PY110/PG36" },
      { name: "Olive Green", hex: "#5A6B2E", pigment: "mixed" },
      { name: "Yellow Ochre", hex: "#C9953B", pigment: "PY43" },
      { name: "Raw Sienna", hex: "#B8833B", pigment: "PY43" },
      { name: "Burnt Sienna", hex: "#8A3B1E", pigment: "PR101" },
      { name: "Light Red", hex: "#B04A2E", pigment: "PR101" },
      { name: "Burnt Umber", hex: "#5C3317", pigment: "PBr7" },
      { name: "Raw Umber", hex: "#6B4E31", pigment: "PBr7" },
      { name: "Sepia", hex: "#4A3020", pigment: "mixed" },
      { name: "Payne's Gray", hex: "#3D4A5C", pigment: "mixed" },
      { name: "Ivory Black", hex: "#1A1A1A", pigment: "PBk9" },
      { name: "Chinese White", hex: "#F5F3EC", pigment: "PW4", acrylicOnly: true },
    ],
  },
  {
    id: "wn-cotman",
    brand: "Winsor & Newton",
    line: "Cotman Watercolour",
    medium: "watercolour",
    note: "Student range — good for planning student-palette mixes.",
    paints: [
      { name: "Lemon Yellow Hue", hex: "#F2E04A" },
      { name: "Cadmium Yellow Pale Hue", hex: "#F5D23A" },
      { name: "Cadmium Yellow Hue", hex: "#F0B820" },
      { name: "Cadmium Orange Hue", hex: "#E87020" },
      { name: "Cadmium Red Pale Hue", hex: "#E84530" },
      { name: "Cadmium Red Hue", hex: "#D4322C" },
      { name: "Alizarin Crimson Hue", hex: "#9B1B30" },
      { name: "Permanent Rose", hex: "#D24A7C" },
      { name: "Purple Lake", hex: "#6B3A6B" },
      { name: "Ultramarine", hex: "#2E4A9B" },
      { name: "Cobalt Blue Hue", hex: "#3A6BB0" },
      { name: "Cerulean Blue Hue", hex: "#3A8BC0" },
      { name: "Intense Blue (Phthalo)", hex: "#005A8C" },
      { name: "Intense Green (Phthalo)", hex: "#008060" },
      { name: "Viridian Hue", hex: "#2E7A66" },
      { name: "Sap Green", hex: "#4F7A2E" },
      { name: "Yellow Ochre", hex: "#C9953B" },
      { name: "Raw Sienna", hex: "#B8833B" },
      { name: "Burnt Sienna", hex: "#8A3B1E" },
      { name: "Burnt Umber", hex: "#5C3317" },
      { name: "Payne's Gray", hex: "#3D4A5C" },
      { name: "Ivory Black", hex: "#1A1A1A" },
    ],
  },
  {
    id: "ds-ef",
    brand: "Daniel Smith",
    line: "Extra Fine Watercolour",
    medium: "watercolour",
    note: "Essentials + popular favourites (incl. granulating favourites).",
    paints: [
      { name: "Hansa Yellow Light", hex: "#F5E04A", pigment: "PY3", note: "Cool yellow" },
      { name: "Hansa Yellow Medium", hex: "#F2C820", pigment: "PY97" },
      { name: "New Gamboge", hex: "#E8A010", pigment: "PY97/PY110", note: "Warm yellow" },
      { name: "Quinacridone Gold", hex: "#D49220", pigment: "PO48/PY150" },
      { name: "Pyrrol Scarlet", hex: "#E23A28", pigment: "PR255", note: "Warm red" },
      { name: "Pyrrol Red", hex: "#D42828", pigment: "PR254" },
      { name: "Quinacridone Rose", hex: "#C4356A", pigment: "PV19", note: "Cool red" },
      { name: "Quinacridone Magenta", hex: "#A61C5C", pigment: "PR122" },
      { name: "Permanent Alizarin Crimson", hex: "#8E1C36", pigment: "PR177" },
      { name: "Carbazole Violet", hex: "#4A2A6B", pigment: "PV23" },
      { name: "French Ultramarine", hex: "#2B4C9B", pigment: "PB29", note: "Warm blue" },
      { name: "Ultramarine Blue", hex: "#2A4A8C", pigment: "PB29" },
      { name: "Cobalt Blue", hex: "#2F5FA8", pigment: "PB28" },
      { name: "Cerulean Blue Chromium", hex: "#2A7EB5", pigment: "PB36" },
      { name: "Phthalo Blue (GS)", hex: "#005A8C", pigment: "PB15:3", note: "Cool blue" },
      { name: "Phthalo Blue (RS)", hex: "#0A3D7A", pigment: "PB15:1" },
      { name: "Indigo", hex: "#1A2E4A", pigment: "mixed" },
      { name: "Phthalo Green (BS)", hex: "#006B5A", pigment: "PG7" },
      { name: "Phthalo Green (YS)", hex: "#0A7A4A", pigment: "PG36" },
      { name: "Sap Green", hex: "#4F7A2E", pigment: "mixed" },
      { name: "Undersea Green", hex: "#3A5A3A", pigment: "mixed", note: "Granulating" },
      { name: "Rich Green Gold", hex: "#8BA82A", pigment: "PY129" },
      { name: "Yellow Ochre", hex: "#C9953B", pigment: "PY43" },
      { name: "Raw Sienna", hex: "#B8833B", pigment: "PBr7" },
      { name: "Burnt Sienna", hex: "#8A3B1E", pigment: "PBr7" },
      { name: "Transparent Red Oxide", hex: "#A33B1E", pigment: "PR101" },
      { name: "Burnt Umber", hex: "#5C3317", pigment: "PBr7" },
      { name: "Raw Umber", hex: "#6B4E31", pigment: "PBr7" },
      { name: "Moonglow", hex: "#4A3A5C", pigment: "mixed", note: "Granulating favourite" },
      { name: "Shadow Violet", hex: "#5A4A5C", pigment: "mixed", note: "Granulating" },
      { name: "Neutral Tint", hex: "#2C2C34", pigment: "mixed" },
      { name: "Lunar Black", hex: "#1A1A1E", pigment: "PBk11", note: "Granulating" },
      { name: "Buff Titanium", hex: "#E8DCC8", pigment: "PW6/PY42" },
    ],
  },
  {
    id: "schmincke-horadam",
    brand: "Schmincke",
    line: "Horadam Aquarell",
    medium: "watercolour",
    note: "Popular Horadam colours for planning.",
    paints: [
      { name: "Lemon Yellow", hex: "#F4E84A", pigment: "PY3" },
      { name: "Cadmium Yellow Light", hex: "#F5D23A", pigment: "PY35" },
      { name: "Cadmium Yellow Deep", hex: "#E8A010", pigment: "PY35" },
      { name: "Indian Yellow", hex: "#E39A18", pigment: "PY153" },
      { name: "Cadmium Orange Deep", hex: "#E85A18", pigment: "PO20" },
      { name: "Cadmium Red Light", hex: "#E23A28", pigment: "PR108" },
      { name: "Cadmium Red Deep", hex: "#C42828", pigment: "PR108" },
      { name: "Ruby Red", hex: "#B01C3A", pigment: "PR264" },
      { name: "Permanent Carmine", hex: "#A61C40", pigment: "PR176" },
      { name: "Magenta", hex: "#A61C5C", pigment: "PR122" },
      { name: "Manganese Violet", hex: "#6B3A6B", pigment: "PV16" },
      { name: "Ultramarine Finest", hex: "#2E4A9B", pigment: "PB29" },
      { name: "Cobalt Blue Light", hex: "#3A6BB0", pigment: "PB28" },
      { name: "Helio Cerulean", hex: "#2A8BC0", pigment: "PB15:3" },
      { name: "Prussian Blue", hex: "#0B2E4A", pigment: "PB27" },
      { name: "Phthalo Green", hex: "#006B5A", pigment: "PG7" },
      { name: "Sap Green", hex: "#4F7A2E", pigment: "mixed" },
      { name: "Olive Green Yellowish", hex: "#6B7A2E", pigment: "mixed" },
      { name: "Yellow Ochre", hex: "#C9953B", pigment: "PY43" },
      { name: "Raw Sienna", hex: "#B8833B", pigment: "PY43" },
      { name: "English Venetian Red", hex: "#A33B2B", pigment: "PR101" },
      { name: "Burnt Sienna", hex: "#8A3B1E", pigment: "PR101" },
      { name: "Burnt Umber", hex: "#5C3317", pigment: "PBr7" },
      { name: "Sepia Brown", hex: "#4A3020", pigment: "mixed" },
      { name: "Payne's Grey Bluish", hex: "#3D4A5C", pigment: "mixed" },
      { name: "Ivory Black", hex: "#1A1A1A", pigment: "PBk9" },
    ],
  },
  {
    id: "sennelier-wc",
    brand: "Sennelier",
    line: "l'Aquarelle",
    medium: "watercolour",
    note: "Honey-based French watercolours — popular planning set.",
    paints: [
      { name: "Lemon Yellow", hex: "#F4E84A", pigment: "PY3" },
      { name: "Cadmium Yellow Light", hex: "#F5D23A", pigment: "PY35" },
      { name: "Indian Yellow", hex: "#E39A18", pigment: "PY153" },
      { name: "Cadmium Yellow Orange", hex: "#E88A18", pigment: "PO20" },
      { name: "Chinese Orange", hex: "#E85A20", pigment: "PO73" },
      { name: "Cadmium Red Light", hex: "#E23A28", pigment: "PR108" },
      { name: "Cadmium Red Purple", hex: "#B02838", pigment: "PR108" },
      { name: "Alizarin Crimson", hex: "#8E1C36", pigment: "PR83" },
      { name: "Permanent Magenta", hex: "#A61C5C", pigment: "PR122" },
      { name: "Cobalt Violet Light Hue", hex: "#9B5A9E", pigment: "mixed" },
      { name: "French Ultramarine Blue", hex: "#2E4A9B", pigment: "PB29" },
      { name: "Cobalt Blue", hex: "#2F5FA8", pigment: "PB28" },
      { name: "Cerulean Blue", hex: "#2A7EB5", pigment: "PB35" },
      { name: "Phthalocyanine Blue", hex: "#005A8C", pigment: "PB15:3" },
      { name: "Indigo", hex: "#1A2E4A", pigment: "mixed" },
      { name: "Phthalocyanine Green Light", hex: "#0A7A4A", pigment: "PG36" },
      { name: "Viridian", hex: "#2E7A66", pigment: "PG18" },
      { name: "Forest Green", hex: "#2E5A2E", pigment: "mixed" },
      { name: "Yellow Ochre", hex: "#C9953B", pigment: "PY43" },
      { name: "Raw Sienna", hex: "#B8833B", pigment: "PBr7" },
      { name: "Burnt Sienna", hex: "#8A3B1E", pigment: "PBr7" },
      { name: "Venetian Red", hex: "#A33B2B", pigment: "PR101" },
      { name: "Burnt Umber", hex: "#5C3317", pigment: "PBr7" },
      { name: "Payne's Grey", hex: "#3D4A5C", pigment: "mixed" },
      { name: "Ivory Black", hex: "#1A1A1A", pigment: "PBk9" },
    ],
  },
  {
    id: "golden-hb",
    brand: "Golden",
    line: "Heavy Body Acrylic",
    medium: "acrylic",
    note: "Popular Heavy Body colours for acrylic planning.",
    paints: [
      { name: "Titanium White", hex: "#F7F5F0", pigment: "PW6" },
      { name: "Zinc White", hex: "#F2F0EA", pigment: "PW4" },
      { name: "Hansa Yellow Light", hex: "#F5E04A", pigment: "PY3" },
      { name: "Hansa Yellow Medium", hex: "#F2C820", pigment: "PY73" },
      { name: "Cadmium Yellow Medium", hex: "#F0B400", pigment: "PY35" },
      { name: "Cadmium Orange", hex: "#E86A1A", pigment: "PO20" },
      { name: "Pyrrole Red Light", hex: "#E23A28", pigment: "PR255" },
      { name: "Pyrrole Red", hex: "#D42828", pigment: "PR254" },
      { name: "Cadmium Red Medium", hex: "#D4322C", pigment: "PR108" },
      { name: "Quinacridone Magenta", hex: "#A61C5C", pigment: "PR122" },
      { name: "Quinacridone Red", hex: "#C4354A", pigment: "PV19" },
      { name: "Alizarin Crimson Hue", hex: "#8E1C36", pigment: "PR177/PR122" },
      { name: "Dioxazine Purple", hex: "#4A2A6B", pigment: "PV23" },
      { name: "Ultramarine Blue", hex: "#2B4C9B", pigment: "PB29" },
      { name: "Cobalt Blue", hex: "#2F5FA8", pigment: "PB28" },
      { name: "Cerulean Blue Chromium", hex: "#2A7EB5", pigment: "PB36" },
      { name: "Phthalo Blue (GS)", hex: "#005A8C", pigment: "PB15:3" },
      { name: "Phthalo Blue (RS)", hex: "#0A3D7A", pigment: "PB15:1" },
      { name: "Phthalo Green (BS)", hex: "#006B5A", pigment: "PG7" },
      { name: "Phthalo Green (YS)", hex: "#0A7A4A", pigment: "PG36" },
      { name: "Sap Green Hue", hex: "#4F7A2E", pigment: "mixed" },
      { name: "Yellow Ochre", hex: "#C9953B", pigment: "PY43" },
      { name: "Raw Sienna", hex: "#B8833B", pigment: "PBr7" },
      { name: "Burnt Sienna", hex: "#8A3B1E", pigment: "PR101" },
      { name: "Transparent Red Iron Oxide", hex: "#A33B1E", pigment: "PR101" },
      { name: "Burnt Umber", hex: "#5C3317", pigment: "PBr7" },
      { name: "Raw Umber", hex: "#6B4E31", pigment: "PBr7" },
      { name: "Carbon Black", hex: "#0D0D0D", pigment: "PBk7" },
      { name: "Bone Black", hex: "#1A1A1A", pigment: "PBk9" },
    ],
  },
  {
    id: "liquitex-hb",
    brand: "Liquitex",
    line: "Heavy Body Acrylic",
    medium: "acrylic",
    note: "Common Liquitex Heavy Body studio colours.",
    paints: [
      { name: "Titanium White", hex: "#F7F5F0", pigment: "PW6" },
      { name: "Cadmium Yellow Light Hue", hex: "#F5D23A" },
      { name: "Cadmium Yellow Medium Hue", hex: "#F0B400" },
      { name: "Cadmium Orange Hue", hex: "#E86A1A" },
      { name: "Cadmium Red Light Hue", hex: "#E23A28" },
      { name: "Cadmium Red Medium Hue", hex: "#D4322C" },
      { name: "Naphthol Crimson", hex: "#C42838", pigment: "PR170" },
      { name: "Quinacridone Magenta", hex: "#A61C5C", pigment: "PR122" },
      { name: "Quinacridone Red", hex: "#C4354A", pigment: "PV19" },
      { name: "Dioxazine Purple", hex: "#4A2A6B", pigment: "PV23" },
      { name: "Ultramarine Blue (Red Shade)", hex: "#2B4C9B", pigment: "PB29" },
      { name: "Cobalt Blue Hue", hex: "#3A6BB0" },
      { name: "Cerulean Blue Hue", hex: "#3A8BC0" },
      { name: "Phthalocyanine Blue (GS)", hex: "#005A8C", pigment: "PB15:3" },
      { name: "Phthalocyanine Green (BS)", hex: "#006B5A", pigment: "PG7" },
      { name: "Brilliant Yellow Green", hex: "#8BC43A" },
      { name: "Light Green Permanent", hex: "#4A9B4A" },
      { name: "Hooker's Green Hue Permanent", hex: "#3A6B3A" },
      { name: "Yellow Oxide", hex: "#C9953B", pigment: "PY42" },
      { name: "Raw Sienna", hex: "#B8833B", pigment: "PBr7" },
      { name: "Burnt Sienna", hex: "#8A3B1E", pigment: "PR101" },
      { name: "Burnt Umber", hex: "#5C3317", pigment: "PBr7" },
      { name: "Raw Umber", hex: "#6B4E31", pigment: "PBr7" },
      { name: "Payne's Gray", hex: "#3D4A5C", pigment: "mixed" },
      { name: "Ivory Black", hex: "#1A1A1A", pigment: "PBk9" },
      { name: "Carbon Black", hex: "#0D0D0D", pigment: "PBk7" },
    ],
  },
  {
    id: "wn-professional-acrylic",
    brand: "Winsor & Newton",
    line: "Professional Acrylic",
    medium: "acrylic",
    note: "W&N Professional Acrylic — shared names with the watercolour line.",
    paints: [
      { name: "Titanium White", hex: "#F7F5F0", pigment: "PW6" },
      { name: "Bismuth Yellow", hex: "#F5E055", pigment: "PY184" },
      { name: "Azo Yellow Medium", hex: "#F2C41A", pigment: "PY74" },
      { name: "Cadmium Yellow Medium", hex: "#F0B400", pigment: "PY35" },
      { name: "Cadmium Orange", hex: "#E86A1A", pigment: "PO20" },
      { name: "Cadmium Red Medium", hex: "#D4322C", pigment: "PR108" },
      { name: "Pyrrole Red", hex: "#D42828", pigment: "PR254" },
      { name: "Permanent Alizarin Crimson", hex: "#8E1C36", pigment: "PR206" },
      { name: "Quinacridone Magenta", hex: "#A61C5C", pigment: "PR122" },
      { name: "Dioxazine Purple", hex: "#4A2A6B", pigment: "PV23" },
      { name: "Ultramarine Blue", hex: "#2B4C9B", pigment: "PB29" },
      { name: "Cobalt Blue", hex: "#2F5FA8", pigment: "PB28" },
      { name: "Cerulean Blue", hex: "#2A7EB5", pigment: "PB35" },
      { name: "Phthalo Blue (Green Shade)", hex: "#005A8C", pigment: "PB15" },
      { name: "Phthalo Green (Blue Shade)", hex: "#006B5A", pigment: "PG7" },
      { name: "Permanent Sap Green", hex: "#3F6B2E" },
      { name: "Yellow Ochre", hex: "#C9953B", pigment: "PY43" },
      { name: "Raw Sienna", hex: "#B8833B", pigment: "PY43" },
      { name: "Burnt Sienna", hex: "#8A3B1E", pigment: "PR101" },
      { name: "Burnt Umber", hex: "#5C3317", pigment: "PBr7" },
      { name: "Raw Umber", hex: "#6B4E31", pigment: "PBr7" },
      { name: "Payne's Gray", hex: "#3D4A5C" },
      { name: "Ivory Black", hex: "#1A1A1A", pigment: "PBk9" },
      { name: "Mars Black", hex: "#141414", pigment: "PBk11" },
    ],
  },

  // ——— Additional watercolour lines ———
  {
    id: "holbein-awc",
    brand: "Holbein",
    line: "Artists' Watercolour",
    medium: "watercolour",
    note: "Japanese Artists' Watercolour — bright, finely milled.",
    paints: [
      { name: "Lemon Yellow", hex: "#F5E84A", pigment: "PY3" },
      { name: "Permanent Yellow Light", hex: "#F5D23A", pigment: "PY154" },
      { name: "Permanent Yellow Deep", hex: "#E8A010", pigment: "PY65" },
      { name: "Yellow Ochre", hex: "#C9953B", pigment: "PY43" },
      { name: "Jaune Brilliant No.2", hex: "#F0C88A", pigment: "mixed" },
      { name: "Cadmium Yellow Orange", hex: "#E88A18", pigment: "PO20" },
      { name: "Cadmium Red Orange", hex: "#E84A28", pigment: "PR108" },
      { name: "Cadmium Red Light", hex: "#E23A28", pigment: "PR108" },
      { name: "Cadmium Red Deep", hex: "#C42828", pigment: "PR108" },
      { name: "Crimson Lake", hex: "#9B1B30", pigment: "PR83" },
      { name: "Opera", hex: "#E83A8A", pigment: "PR122/BV10", note: "Bright fluorescent-leaning rose" },
      { name: "Permanent Rose", hex: "#D24A7C", pigment: "PV19" },
      { name: "Quinacridone Magenta", hex: "#A61C5C", pigment: "PR122" },
      { name: "Mineral Violet", hex: "#6B3A6B", pigment: "PV16" },
      { name: "Ultramarine Deep", hex: "#2A3A8C", pigment: "PB29" },
      { name: "Cobalt Blue", hex: "#2F5FA8", pigment: "PB28" },
      { name: "Cerulean Blue", hex: "#2A7EB5", pigment: "PB35" },
      { name: "Compose Blue", hex: "#3A8BB8", pigment: "mixed" },
      { name: "Prussian Blue", hex: "#0B2E4A", pigment: "PB27" },
      { name: "Phthalo Blue", hex: "#005A8C", pigment: "PB15" },
      { name: "Viridian Hue", hex: "#2E7A66", pigment: "PG7" },
      { name: "Hooker's Green", hex: "#3A6B3A", pigment: "mixed" },
      { name: "Sap Green", hex: "#4F7A2E", pigment: "mixed" },
      { name: "Olive Green", hex: "#5A6B2E", pigment: "mixed" },
      { name: "Raw Sienna", hex: "#B8833B", pigment: "PY43" },
      { name: "Burnt Sienna", hex: "#8A3B1E", pigment: "PR101" },
      { name: "Burnt Umber", hex: "#5C3317", pigment: "PBr7" },
      { name: "Sepia", hex: "#4A3020", pigment: "mixed" },
      { name: "Payne's Grey", hex: "#3D4A5C", pigment: "mixed" },
      { name: "Ivory Black", hex: "#1A1A1A", pigment: "PBk9" },
    ],
  },
  {
    id: "mgraham-wc",
    brand: "M. Graham",
    line: "Artists' Watercolour",
    medium: "watercolour",
    note: "Honey-based USA watercolours — rich, rewettable.",
    paints: [
      { name: "Azo Yellow", hex: "#F2C41A", pigment: "PY151" },
      { name: "Hansa Yellow", hex: "#F5D031", pigment: "PY3" },
      { name: "Cadmium Yellow", hex: "#F0B400", pigment: "PY35" },
      { name: "Nickel Azo Yellow", hex: "#D4A010", pigment: "PY150" },
      { name: "Cadmium Orange", hex: "#E86A1A", pigment: "PO20" },
      { name: "Pyrrol Red", hex: "#D42828", pigment: "PR254" },
      { name: "Cadmium Red", hex: "#D4322C", pigment: "PR108" },
      { name: "Naphthol Red", hex: "#C42838", pigment: "PR112" },
      { name: "Quinacridone Rose", hex: "#C4356A", pigment: "PV19" },
      { name: "Quinacridone Red", hex: "#C4354A", pigment: "PV19" },
      { name: "Quinacridone Violet", hex: "#8B2A6B", pigment: "PV19" },
      { name: "Ultramarine Blue", hex: "#2B4C9B", pigment: "PB29" },
      { name: "Cobalt Blue", hex: "#2F5FA8", pigment: "PB28" },
      { name: "Cerulean Blue", hex: "#2A7EB5", pigment: "PB36" },
      { name: "Phthalocyanine Blue", hex: "#005A8C", pigment: "PB15:3" },
      { name: "Prussian Blue", hex: "#0B2E4A", pigment: "PB27" },
      { name: "Phthalocyanine Green", hex: "#006B5A", pigment: "PG7" },
      { name: "Viridian", hex: "#2E7A66", pigment: "PG18" },
      { name: "Hooker's Green", hex: "#3A6B3A", pigment: "mixed" },
      { name: "Azo Green", hex: "#6B9B2E", pigment: "PY129" },
      { name: "Yellow Ochre", hex: "#C9953B", pigment: "PY43" },
      { name: "Raw Sienna", hex: "#B8833B", pigment: "PBr7" },
      { name: "Burnt Sienna", hex: "#8A3B1E", pigment: "PBr7" },
      { name: "Transparent Red Iron Oxide", hex: "#A33B1E", pigment: "PR101" },
      { name: "Burnt Umber", hex: "#5C3317", pigment: "PBr7" },
      { name: "Raw Umber", hex: "#6B4E31", pigment: "PBr7" },
      { name: "Neutral Tint", hex: "#2C2C34", pigment: "mixed" },
      { name: "Ivory Black", hex: "#1A1A1A", pigment: "PBk9" },
    ],
  },
  {
    id: "rembrandt-wc",
    brand: "Rembrandt",
    line: "Extra Fine Watercolour",
    medium: "watercolour",
    note: "Royal Talens Rembrandt — European professional range.",
    paints: [
      { name: "Permanent Lemon Yellow", hex: "#F4E84A", pigment: "PY184" },
      { name: "Azo Yellow Light", hex: "#F5D23A", pigment: "PY154" },
      { name: "Azo Yellow Deep", hex: "#E8A010", pigment: "PY65" },
      { name: "Indian Yellow", hex: "#E39A18", pigment: "PY110" },
      { name: "Permanent Orange", hex: "#E86A1A", pigment: "PO73" },
      { name: "Permanent Red Light", hex: "#E23A28", pigment: "PR255" },
      { name: "Permanent Red Deep", hex: "#C42828", pigment: "PR254" },
      { name: "Permanent Madder Lake", hex: "#8E1C36", pigment: "PR264" },
      { name: "Quinacridone Rose", hex: "#C4356A", pigment: "PV19" },
      { name: "Permanent Red Violet", hex: "#A61C5C", pigment: "PR122" },
      { name: "Permanent Blue Violet", hex: "#5A3A8C", pigment: "PV23" },
      { name: "Ultramarine Deep", hex: "#2A3A8C", pigment: "PB29" },
      { name: "Cobalt Blue (Ultramarine)", hex: "#2F5FA8", pigment: "PB28" },
      { name: "Cerulean Blue Phthalo", hex: "#2A8BC0", pigment: "PB15" },
      { name: "Phthalo Blue Red", hex: "#0A3D7A", pigment: "PB15:1" },
      { name: "Indigo", hex: "#1A2E4A", pigment: "mixed" },
      { name: "Phthalo Green", hex: "#006B5A", pigment: "PG7" },
      { name: "Permanent Green", hex: "#2E8A4A", pigment: "mixed" },
      { name: "Sap Green", hex: "#4F7A2E", pigment: "mixed" },
      { name: "Olive Green", hex: "#5A6B2E", pigment: "mixed" },
      { name: "Yellow Ochre", hex: "#C9953B", pigment: "PY43" },
      { name: "Raw Sienna", hex: "#B8833B", pigment: "PY43" },
      { name: "Burnt Sienna", hex: "#8A3B1E", pigment: "PR101" },
      { name: "Burnt Umber", hex: "#5C3317", pigment: "PBr7" },
      { name: "Raw Umber", hex: "#6B4E31", pigment: "PBr7" },
      { name: "Sepia", hex: "#4A3020", pigment: "mixed" },
      { name: "Payne's Grey", hex: "#3D4A5C", pigment: "mixed" },
      { name: "Oxide Black", hex: "#1A1A1A", pigment: "PBk11" },
    ],
  },
  {
    id: "white-nights",
    brand: "White Nights",
    line: "Extra Fine Watercolour",
    medium: "watercolour",
    note: "St. Petersburg (Nevskaya Palitra) — popular pan/tube range.",
    paints: [
      { name: "Lemon", hex: "#F4E84A", pigment: "PY3" },
      { name: "Cadmium Yellow Medium", hex: "#F0B400", pigment: "PY35" },
      { name: "Yellow Ochre", hex: "#C9953B", pigment: "PY43" },
      { name: "Golden Deep", hex: "#E8A010", pigment: "PY65" },
      { name: "Orange", hex: "#E86A1A", pigment: "PO13" },
      { name: "Cadmium Red Light", hex: "#E23A28", pigment: "PR108" },
      { name: "Scarlet", hex: "#D93A2E", pigment: "PR4" },
      { name: "Carmine", hex: "#A61C40", pigment: "PR170" },
      { name: "Ruby", hex: "#9B1B30", pigment: "PR170" },
      { name: "Quinacridone Rose", hex: "#C4356A", pigment: "PV19" },
      { name: "Quinacridone Lilac", hex: "#8B4A8C", pigment: "PR122" },
      { name: "Violet", hex: "#5A3A8C", pigment: "PV23" },
      { name: "Ultramarine", hex: "#2E4A9B", pigment: "PB29" },
      { name: "Cobalt Blue", hex: "#2F5FA8", pigment: "PB28" },
      { name: "Blue", hex: "#1A4A8C", pigment: "PB15" },
      { name: "Indigo", hex: "#1A2E4A", pigment: "mixed" },
      { name: "Turquoise Blue", hex: "#1A7A8C", pigment: "PB15/PG7" },
      { name: "Green", hex: "#2E8A4A", pigment: "PG7" },
      { name: "Emerald Green", hex: "#0A7A4A", pigment: "PG7" },
      { name: "Yellow Green", hex: "#6B9B2E", pigment: "mixed" },
      { name: "Olive Green", hex: "#5A6B2E", pigment: "mixed" },
      { name: "Raw Sienna", hex: "#B8833B", pigment: "PBr7" },
      { name: "Burnt Sienna", hex: "#8A3B1E", pigment: "PBr7" },
      { name: "English Red", hex: "#A33B2B", pigment: "PR101" },
      { name: "Burnt Umber", hex: "#5C3317", pigment: "PBr7" },
      { name: "Sepia", hex: "#4A3020", pigment: "mixed" },
      { name: "Payne's Grey", hex: "#3D4A5C", pigment: "mixed" },
      { name: "Neutral Black", hex: "#1A1A1A", pigment: "PBk7" },
    ],
  },
  {
    id: "qor-wc",
    brand: "QoR",
    line: "Modern Watercolor (Golden)",
    medium: "watercolour",
    note: "Golden's QoR — Aquazol binder, modern high-chroma range.",
    paints: [
      { name: "Nickel Azo Yellow", hex: "#D4A010", pigment: "PY150" },
      { name: "Hansa Yellow Light", hex: "#F5E04A", pigment: "PY3" },
      { name: "Cadmium Yellow Primrose", hex: "#F5D23A", pigment: "PY35" },
      { name: "Indian Yellow", hex: "#E39A18", pigment: "PY110" },
      { name: "Cadmium Orange", hex: "#E86A1A", pigment: "PO20" },
      { name: "Pyrrole Red Light", hex: "#E23A28", pigment: "PR255" },
      { name: "Pyrrole Red", hex: "#D42828", pigment: "PR254" },
      { name: "Quinacridone Magenta", hex: "#A61C5C", pigment: "PR122" },
      { name: "Quinacridone Red", hex: "#C4354A", pigment: "PV19" },
      { name: "Permanent Alizarin Crimson", hex: "#8E1C36", pigment: "PR177" },
      { name: "Dioxazine Purple", hex: "#4A2A6B", pigment: "PV23" },
      { name: "Ultramarine Blue", hex: "#2B4C9B", pigment: "PB29" },
      { name: "Cobalt Blue", hex: "#2F5FA8", pigment: "PB28" },
      { name: "Cerulean Blue Chromium", hex: "#2A7EB5", pigment: "PB36" },
      { name: "Phthalo Blue (GS)", hex: "#005A8C", pigment: "PB15:3" },
      { name: "Phthalo Blue (RS)", hex: "#0A3D7A", pigment: "PB15:1" },
      { name: "Indigo", hex: "#1A2E4A", pigment: "mixed" },
      { name: "Phthalo Green (BS)", hex: "#006B5A", pigment: "PG7" },
      { name: "Viridian", hex: "#2E7A66", pigment: "PG18" },
      { name: "Sap Green", hex: "#4F7A2E", pigment: "mixed" },
      { name: "Green Gold", hex: "#8BA82A", pigment: "PY129" },
      { name: "Yellow Ochre", hex: "#C9953B", pigment: "PY43" },
      { name: "Raw Sienna", hex: "#B8833B", pigment: "PBr7" },
      { name: "Burnt Sienna", hex: "#8A3B1E", pigment: "PR101" },
      { name: "Transparent Red Oxide", hex: "#A33B1E", pigment: "PR101" },
      { name: "Burnt Umber", hex: "#5C3317", pigment: "PBr7" },
      { name: "Payne's Gray", hex: "#3D4A5C", pigment: "mixed" },
      { name: "Neutral Tint", hex: "#2C2C34", pigment: "mixed" },
    ],
  },
  {
    id: "mission-gold",
    brand: "Mijello",
    line: "Mission Gold Watercolour",
    medium: "watercolour",
    note: "Korean Mission Gold — bright, popular half-pan sets.",
    paints: [
      { name: "Lemon Yellow", hex: "#F4E84A", pigment: "PY3" },
      { name: "Permanent Yellow Light", hex: "#F5D23A", pigment: "PY154" },
      { name: "Permanent Yellow Deep", hex: "#E8A010", pigment: "PY65" },
      { name: "Yellow Ochre", hex: "#C9953B", pigment: "PY42" },
      { name: "Permanent Orange", hex: "#E86A1A", pigment: "PO73" },
      { name: "Permanent Red Light", hex: "#E23A28", pigment: "PR255" },
      { name: "Permanent Red Deep", hex: "#C42828", pigment: "PR254" },
      { name: "Permanent Rose", hex: "#D24A7C", pigment: "PV19" },
      { name: "Opera Pink", hex: "#E83A8A", pigment: "PR122" },
      { name: "Permanent Magenta", hex: "#A61C5C", pigment: "PR122" },
      { name: "Permanent Violet", hex: "#5A3A8C", pigment: "PV23" },
      { name: "Ultramarine Deep", hex: "#2A3A8C", pigment: "PB29" },
      { name: "Cobalt Blue", hex: "#2F5FA8", pigment: "PB28" },
      { name: "Cerulean Blue", hex: "#2A7EB5", pigment: "PB35" },
      { name: "Peacock Blue", hex: "#1A7A9B", pigment: "PB15" },
      { name: "Prussian Blue", hex: "#0B2E4A", pigment: "PB27" },
      { name: "Viridian", hex: "#2E7A66", pigment: "PG18" },
      { name: "Hooker's Green", hex: "#3A6B3A", pigment: "mixed" },
      { name: "Sap Green", hex: "#4F7A2E", pigment: "mixed" },
      { name: "Olive Green", hex: "#5A6B2E", pigment: "mixed" },
      { name: "Raw Sienna", hex: "#B8833B", pigment: "PY42" },
      { name: "Burnt Sienna", hex: "#8A3B1E", pigment: "PR101" },
      { name: "Burnt Umber", hex: "#5C3317", pigment: "PBr7" },
      { name: "Van Dyke Brown", hex: "#4A3020", pigment: "mixed" },
      { name: "Payne's Grey", hex: "#3D4A5C", pigment: "mixed" },
      { name: "Ivory Black", hex: "#1A1A1A", pigment: "PBk9" },
    ],
  },
  {
    id: "roman-szmal",
    brand: "Roman Szmal",
    line: "Aquarius Watercolour",
    medium: "watercolour",
    note: "Polish Aquarius — strong granulating and earth range.",
    paints: [
      { name: "Hansa Yellow Light", hex: "#F5E04A", pigment: "PY3" },
      { name: "Isoindolinone Yellow", hex: "#F2C41A", pigment: "PY110" },
      { name: "Indian Yellow", hex: "#E39A18", pigment: "PY153" },
      { name: "Pyrrole Orange", hex: "#E85A20", pigment: "PO73" },
      { name: "Pyrrole Red", hex: "#D42828", pigment: "PR254" },
      { name: "Pyrrole Scarlet", hex: "#E23A28", pigment: "PR255" },
      { name: "Quinacridone Rose", hex: "#C4356A", pigment: "PV19" },
      { name: "Quinacridone Magenta", hex: "#A61C5C", pigment: "PR122" },
      { name: "Dioxazine Violet", hex: "#4A2A6B", pigment: "PV23" },
      { name: "French Ultramarine", hex: "#2B4C9B", pigment: "PB29" },
      { name: "Cobalt Blue", hex: "#2F5FA8", pigment: "PB28" },
      { name: "Cerulean Blue", hex: "#2A7EB5", pigment: "PB35" },
      { name: "Phthalo Blue GS", hex: "#005A8C", pigment: "PB15:3" },
      { name: "Indigo", hex: "#1A2E4A", pigment: "mixed" },
      { name: "Phthalo Green BS", hex: "#006B5A", pigment: "PG7" },
      { name: "Sap Green", hex: "#4F7A2E", pigment: "mixed" },
      { name: "Green Apatite Genuine", hex: "#3A6B3A", pigment: "natural", note: "Granulating" },
      { name: "Yellow Ochre", hex: "#C9953B", pigment: "PY43" },
      { name: "Raw Sienna", hex: "#B8833B", pigment: "PBr7" },
      { name: "Burnt Sienna", hex: "#8A3B1E", pigment: "PR101" },
      { name: "Venetian Red", hex: "#A33B2B", pigment: "PR101" },
      { name: "Burnt Umber", hex: "#5C3317", pigment: "PBr7" },
      { name: "Raw Umber", hex: "#6B4E31", pigment: "PBr7" },
      { name: "Caput Mortuum", hex: "#6B2E2E", pigment: "PR101" },
      { name: "Neutral Tint", hex: "#2C2C34", pigment: "mixed" },
      { name: "Ivory Black", hex: "#1A1A1A", pigment: "PBk9" },
    ],
  },
  {
    id: "daler-rowney-awc",
    brand: "Daler-Rowney",
    line: "Artists' Watercolour",
    medium: "watercolour",
    note: "UK Artists' Watercolour — solid studio staples.",
    paints: [
      { name: "Lemon Yellow", hex: "#F4E84A", pigment: "PY3" },
      { name: "Cadmium Yellow Pale", hex: "#F5D23A", pigment: "PY35" },
      { name: "Cadmium Yellow", hex: "#F0B400", pigment: "PY35" },
      { name: "Indian Yellow", hex: "#E39A18", pigment: "PY153" },
      { name: "Cadmium Orange", hex: "#E86A1A", pigment: "PO20" },
      { name: "Cadmium Red", hex: "#D4322C", pigment: "PR108" },
      { name: "Spectrum Red", hex: "#D92B2B", pigment: "PR254" },
      { name: "Alizarin Crimson", hex: "#9B1B30", pigment: "PR83" },
      { name: "Permanent Rose", hex: "#D24A7C", pigment: "PV19" },
      { name: "Quinacridone Magenta", hex: "#A61C5C", pigment: "PR122" },
      { name: "Cobalt Violet", hex: "#8B5A9E", pigment: "PV14" },
      { name: "French Ultramarine", hex: "#2E4A9B", pigment: "PB29" },
      { name: "Cobalt Blue", hex: "#2F5FA8", pigment: "PB28" },
      { name: "Cerulean Blue", hex: "#2A7EB5", pigment: "PB35" },
      { name: "Coeruleum", hex: "#3A8BC0", pigment: "PB35" },
      { name: "Phthalo Blue", hex: "#005A8C", pigment: "PB15" },
      { name: "Indigo", hex: "#1A2E4A", pigment: "mixed" },
      { name: "Viridian", hex: "#2E7A66", pigment: "PG18" },
      { name: "Hooker's Green Dark", hex: "#2E5A2E", pigment: "mixed" },
      { name: "Sap Green", hex: "#4F7A2E", pigment: "mixed" },
      { name: "Yellow Ochre", hex: "#C9953B", pigment: "PY43" },
      { name: "Raw Sienna", hex: "#B8833B", pigment: "PY43" },
      { name: "Burnt Sienna", hex: "#8A3B1E", pigment: "PR101" },
      { name: "Light Red", hex: "#B04A2E", pigment: "PR101" },
      { name: "Burnt Umber", hex: "#5C3317", pigment: "PBr7" },
      { name: "Vandyke Brown", hex: "#4A3020", pigment: "mixed" },
      { name: "Payne's Grey", hex: "#3D4A5C", pigment: "mixed" },
      { name: "Ivory Black", hex: "#1A1A1A", pigment: "PBk9" },
    ],
  },

  // ——— Additional acrylic lines ———
  {
    id: "amsterdam-standard",
    brand: "Amsterdam",
    line: "Standard Series Acrylic",
    medium: "acrylic",
    note: "Royal Talens Amsterdam — affordable studio acrylics.",
    paints: [
      { name: "Titanium White", hex: "#F7F5F0", pigment: "PW6" },
      { name: "Primary Yellow", hex: "#F5D23A", pigment: "PY74" },
      { name: "Azo Yellow Light", hex: "#F5E04A", pigment: "PY3" },
      { name: "Azo Yellow Deep", hex: "#E8A010", pigment: "PY65" },
      { name: "Azo Orange", hex: "#E86A1A", pigment: "PO73" },
      { name: "Naphthol Red Light", hex: "#E23A28", pigment: "PR112" },
      { name: "Naphthol Red Medium", hex: "#D4322C", pigment: "PR170" },
      { name: "Carmine", hex: "#A61C40", pigment: "PR170" },
      { name: "Primary Magenta", hex: "#A61C5C", pigment: "PR122" },
      { name: "Permanent Blue Violet", hex: "#5A3A8C", pigment: "PV23" },
      { name: "Ultramarine", hex: "#2B4C9B", pigment: "PB29" },
      { name: "Primary Cyan", hex: "#0088B8", pigment: "PB15:3" },
      { name: "Phthalo Blue", hex: "#005A8C", pigment: "PB15" },
      { name: "Brilliant Blue", hex: "#3A6BB0", pigment: "mixed" },
      { name: "Phthalo Green", hex: "#006B5A", pigment: "PG7" },
      { name: "Permanent Green Light", hex: "#4A9B4A", pigment: "mixed" },
      { name: "Olive Green Deep", hex: "#4A5A2E", pigment: "mixed" },
      { name: "Yellow Ochre", hex: "#C9953B", pigment: "PY42" },
      { name: "Raw Sienna", hex: "#B8833B", pigment: "PY42" },
      { name: "Burnt Sienna", hex: "#8A3B1E", pigment: "PR101" },
      { name: "Burnt Umber", hex: "#5C3317", pigment: "PBr7" },
      { name: "Raw Umber", hex: "#6B4E31", pigment: "PBr7" },
      { name: "Payne's Grey", hex: "#3D4A5C", pigment: "mixed" },
      { name: "Oxide Black", hex: "#1A1A1A", pigment: "PBk11" },
    ],
  },
  {
    id: "wn-galeria",
    brand: "Winsor & Newton",
    line: "Galeria Acrylic",
    medium: "acrylic",
    note: "Student/studio Galeria — good planning set for beginners.",
    paints: [
      { name: "Titanium White", hex: "#F7F5F0", pigment: "PW6" },
      { name: "Lemon Yellow", hex: "#F4E84A" },
      { name: "Cadmium Yellow Medium Hue", hex: "#F0B400" },
      { name: "Cadmium Orange Hue", hex: "#E86A1A" },
      { name: "Cadmium Red Hue", hex: "#D4322C" },
      { name: "Vermilion Hue", hex: "#E23A28" },
      { name: "Alizarin Crimson Hue", hex: "#9B1B30" },
      { name: "Permanent Rose", hex: "#D24A7C" },
      { name: "Process Magenta", hex: "#A61C5C" },
      { name: "Dioxazine Purple", hex: "#4A2A6B" },
      { name: "Ultramarine", hex: "#2B4C9B" },
      { name: "Cobalt Blue Hue", hex: "#3A6BB0" },
      { name: "Cerulean Blue Hue", hex: "#3A8BC0" },
      { name: "Process Cyan", hex: "#0088B8" },
      { name: "Winsor Blue", hex: "#005A8C" },
      { name: "Winsor Green", hex: "#006B5A" },
      { name: "Permanent Green Light", hex: "#4A9B4A" },
      { name: "Sap Green", hex: "#4F7A2E" },
      { name: "Yellow Ochre", hex: "#C9953B" },
      { name: "Raw Sienna", hex: "#B8833B" },
      { name: "Burnt Sienna", hex: "#8A3B1E" },
      { name: "Burnt Umber", hex: "#5C3317" },
      { name: "Raw Umber", hex: "#6B4E31" },
      { name: "Payne's Gray", hex: "#3D4A5C" },
      { name: "Ivory Black", hex: "#1A1A1A" },
      { name: "Mars Black", hex: "#141414" },
    ],
  },
  {
    id: "matisse-structure",
    brand: "Matisse",
    line: "Structure Acrylic",
    medium: "acrylic",
    note: "Australian Matisse Structure — high pigment load.",
    paints: [
      { name: "Titanium White", hex: "#F7F5F0", pigment: "PW6" },
      { name: "Australian Yellow Light", hex: "#F5E04A", pigment: "PY3" },
      { name: "Australian Yellow Deep", hex: "#E8A010", pigment: "PY65" },
      { name: "Cadmium Yellow Medium", hex: "#F0B400", pigment: "PY35" },
      { name: "Cadmium Orange", hex: "#E86A1A", pigment: "PO20" },
      { name: "Matisse Scarlet", hex: "#E23A28", pigment: "PR255" },
      { name: "Cadmium Red Medium", hex: "#D4322C", pigment: "PR108" },
      { name: "Brilliant Alizarin", hex: "#8E1C36", pigment: "PR177" },
      { name: "Magenta", hex: "#A61C5C", pigment: "PR122" },
      { name: "Dioxazine Purple", hex: "#4A2A6B", pigment: "PV23" },
      { name: "Ultramarine Blue", hex: "#2B4C9B", pigment: "PB29" },
      { name: "Cobalt Blue", hex: "#2F5FA8", pigment: "PB28" },
      { name: "Australian Sky Blue", hex: "#3A8BC0", pigment: "PB15" },
      { name: "Phthalo Blue", hex: "#005A8C", pigment: "PB15:3" },
      { name: "Phthalo Green", hex: "#006B5A", pigment: "PG7" },
      { name: "Australian Sap Green", hex: "#4F7A2E", pigment: "mixed" },
      { name: "Green Light", hex: "#6B9B2E", pigment: "mixed" },
      { name: "Yellow Oxide", hex: "#C9953B", pigment: "PY42" },
      { name: "Raw Sienna", hex: "#B8833B", pigment: "PBr7" },
      { name: "Burnt Sienna", hex: "#8A3B1E", pigment: "PR101" },
      { name: "Burnt Umber", hex: "#5C3317", pigment: "PBr7" },
      { name: "Raw Umber", hex: "#6B4E31", pigment: "PBr7" },
      { name: "Carbon Black", hex: "#0D0D0D", pigment: "PBk7" },
    ],
  },
  {
    id: "atelier-interactive",
    brand: "Atelier",
    line: "Interactive Acrylic",
    medium: "acrylic",
    note: "Chroma Atelier Interactive — stay-wet acrylic system.",
    paints: [
      { name: "Titanium White", hex: "#F7F5F0", pigment: "PW6" },
      { name: "Arylamide Yellow Light", hex: "#F5E04A", pigment: "PY3" },
      { name: "Arylamide Yellow Deep", hex: "#E8A010", pigment: "PY65" },
      { name: "Cadmium Yellow Medium", hex: "#F0B400", pigment: "PY35" },
      { name: "Cadmium Orange", hex: "#E86A1A", pigment: "PO20" },
      { name: "Napthol Red Light", hex: "#E23A28", pigment: "PR112" },
      { name: "Cadmium Red Medium", hex: "#D4322C", pigment: "PR108" },
      { name: "Permanent Alizarin", hex: "#8E1C36", pigment: "PR177" },
      { name: "Quinacridone Magenta", hex: "#A61C5C", pigment: "PR122" },
      { name: "Dioxazine Purple", hex: "#4A2A6B", pigment: "PV23" },
      { name: "French Ultramarine Blue", hex: "#2B4C9B", pigment: "PB29" },
      { name: "Cobalt Blue", hex: "#2F5FA8", pigment: "PB28" },
      { name: "Cerulean Blue", hex: "#2A7EB5", pigment: "PB35" },
      { name: "Phthalo Blue", hex: "#005A8C", pigment: "PB15" },
      { name: "Phthalo Green", hex: "#006B5A", pigment: "PG7" },
      { name: "Permanent Green Light", hex: "#4A9B4A", pigment: "mixed" },
      { name: "Sap Green", hex: "#4F7A2E", pigment: "mixed" },
      { name: "Yellow Ochre", hex: "#C9953B", pigment: "PY43" },
      { name: "Raw Sienna", hex: "#B8833B", pigment: "PBr7" },
      { name: "Burnt Sienna", hex: "#8A3B1E", pigment: "PR101" },
      { name: "Burnt Umber", hex: "#5C3317", pigment: "PBr7" },
      { name: "Raw Umber", hex: "#6B4E31", pigment: "PBr7" },
      { name: "Payne's Grey", hex: "#3D4A5C", pigment: "mixed" },
      { name: "Carbon Black", hex: "#0D0D0D", pigment: "PBk7" },
    ],
  },
  {
    id: "pebeo-studio",
    brand: "Pébéo",
    line: "Studio Acrylics",
    medium: "acrylic",
    note: "French Pébéo Studio — common European student/studio line.",
    paints: [
      { name: "Titanium White", hex: "#F7F5F0", pigment: "PW6" },
      { name: "Primary Cadmium Yellow Hue", hex: "#F5D23A" },
      { name: "Cadmium Yellow Dark Hue", hex: "#E8A010" },
      { name: "Cadmium Orange Hue", hex: "#E86A1A" },
      { name: "Cadmium Red Hue", hex: "#D4322C" },
      { name: "Naphtol Crimson", hex: "#C42838" },
      { name: "Primary Magenta", hex: "#A61C5C" },
      { name: "Dark Ultramarine Blue", hex: "#2A3A8C" },
      { name: "Primary Cyan", hex: "#0088B8" },
      { name: "Phthalocyanine Blue", hex: "#005A8C" },
      { name: "Cobalt Blue Hue", hex: "#3A6BB0" },
      { name: "Phthalocyanine Green", hex: "#006B5A" },
      { name: "Light Green", hex: "#4A9B4A" },
      { name: "Yellow Ochre", hex: "#C9953B" },
      { name: "Raw Sienna", hex: "#B8833B" },
      { name: "Burnt Sienna", hex: "#8A3B1E" },
      { name: "Burnt Umber", hex: "#5C3317" },
      { name: "Raw Umber", hex: "#6B4E31" },
      { name: "Payne's Grey", hex: "#3D4A5C" },
      { name: "Mars Black", hex: "#141414" },
    ],
  },
  {
    id: "holbein-acrylic",
    brand: "Holbein",
    line: "Heavy Body Acrylic",
    medium: "acrylic",
    note: "Holbein Heavy Body Acrylic — fine Japanese mill.",
    paints: [
      { name: "Titanium White", hex: "#F7F5F0", pigment: "PW6" },
      { name: "Lemon Yellow", hex: "#F4E84A", pigment: "PY3" },
      { name: "Permanent Yellow Light", hex: "#F5D23A", pigment: "PY154" },
      { name: "Permanent Yellow Deep", hex: "#E8A010", pigment: "PY65" },
      { name: "Jaune Brilliant", hex: "#F0C88A", pigment: "mixed" },
      { name: "Cadmium Orange", hex: "#E86A1A", pigment: "PO20" },
      { name: "Cadmium Red Light", hex: "#E23A28", pigment: "PR108" },
      { name: "Cadmium Red Deep", hex: "#C42828", pigment: "PR108" },
      { name: "Crimson Lake", hex: "#9B1B30", pigment: "PR83" },
      { name: "Opera", hex: "#E83A8A", pigment: "PR122" },
      { name: "Permanent Rose", hex: "#D24A7C", pigment: "PV19" },
      { name: "Quinacridone Magenta", hex: "#A61C5C", pigment: "PR122" },
      { name: "Mineral Violet", hex: "#6B3A6B", pigment: "PV16" },
      { name: "Ultramarine Deep", hex: "#2A3A8C", pigment: "PB29" },
      { name: "Cobalt Blue", hex: "#2F5FA8", pigment: "PB28" },
      { name: "Cerulean Blue", hex: "#2A7EB5", pigment: "PB35" },
      { name: "Compose Blue", hex: "#3A8BB8", pigment: "mixed" },
      { name: "Phthalo Blue", hex: "#005A8C", pigment: "PB15" },
      { name: "Viridian Hue", hex: "#2E7A66", pigment: "PG7" },
      { name: "Hooker's Green", hex: "#3A6B3A", pigment: "mixed" },
      { name: "Sap Green", hex: "#4F7A2E", pigment: "mixed" },
      { name: "Yellow Ochre", hex: "#C9953B", pigment: "PY43" },
      { name: "Burnt Sienna", hex: "#8A3B1E", pigment: "PR101" },
      { name: "Burnt Umber", hex: "#5C3317", pigment: "PBr7" },
      { name: "Payne's Grey", hex: "#3D4A5C", pigment: "mixed" },
      { name: "Ivory Black", hex: "#1A1A1A", pigment: "PBk9" },
    ],
  },
  {
    id: "blick-artists-acrylic",
    brand: "Blick",
    line: "Artists' Acrylic",
    medium: "acrylic",
    note: "Blick Artists' Acrylic — common US student/pro hybrid.",
    paints: [
      { name: "Titanium White", hex: "#F7F5F0", pigment: "PW6" },
      { name: "Hansa Yellow Light", hex: "#F5E04A", pigment: "PY3" },
      { name: "Hansa Yellow Medium", hex: "#F2C820", pigment: "PY73" },
      { name: "Cadmium Yellow Medium Hue", hex: "#F0B400" },
      { name: "Cadmium Orange Hue", hex: "#E86A1A" },
      { name: "Naphthol Red Light", hex: "#E23A28", pigment: "PR112" },
      { name: "Cadmium Red Medium Hue", hex: "#D4322C" },
      { name: "Quinacridone Magenta", hex: "#A61C5C", pigment: "PR122" },
      { name: "Quinacridone Red", hex: "#C4354A", pigment: "PV19" },
      { name: "Dioxazine Purple", hex: "#4A2A6B", pigment: "PV23" },
      { name: "Ultramarine Blue", hex: "#2B4C9B", pigment: "PB29" },
      { name: "Cobalt Blue Hue", hex: "#3A6BB0" },
      { name: "Cerulean Blue Hue", hex: "#3A8BC0" },
      { name: "Phthalo Blue", hex: "#005A8C", pigment: "PB15:3" },
      { name: "Phthalo Green", hex: "#006B5A", pigment: "PG7" },
      { name: "Hooker's Green Hue", hex: "#3A6B3A" },
      { name: "Sap Green Hue", hex: "#4F7A2E" },
      { name: "Yellow Ochre", hex: "#C9953B", pigment: "PY43" },
      { name: "Raw Sienna", hex: "#B8833B", pigment: "PBr7" },
      { name: "Burnt Sienna", hex: "#8A3B1E", pigment: "PR101" },
      { name: "Burnt Umber", hex: "#5C3317", pigment: "PBr7" },
      { name: "Raw Umber", hex: "#6B4E31", pigment: "PBr7" },
      { name: "Payne's Gray", hex: "#3D4A5C" },
      { name: "Ivory Black", hex: "#1A1A1A", pigment: "PBk9" },
      { name: "Mars Black", hex: "#141414", pigment: "PBk11" },
    ],
  },
];

window.GROUNDS = {
  "paper-white": { name: "Paper white", hex: "#FFFEFA" },
  "paper-cream": { name: "Cream paper", hex: "#F5EDE0" },
  "paper-cold": { name: "Cold-press grey", hex: "#E8E6E1" },
  canvas: { name: "Canvas tone", hex: "#E8DCC8" },
  "mid-grey": { name: "Mid grey underpainting", hex: "#8A8680" },
};

window.MODE_TIPS = {
  watercolour: [
    "Lighten with water, not white. The paper is your lightest value — let it glow through the wash.",
    "Transparent pigments mix cleaner. Opaque or sedimentary colours can chalk or mud when overmixed.",
    "Two or three colours are usually enough. A fourth often greys the mix toward mud.",
    "Complementary pairs (e.g. ultramarine + burnt sienna) make beautiful neutrals — stop before they go dead grey.",
    "Glaze wet-over-dry for optical depth. Each dry layer adds richness without stirring mud on the palette.",
    "Phthalo blues and greens are high-tinting. Start with a tiny part and add more — easier than rescuing a flooded mix.",
    "Warm + cool of the same family (e.g. two yellows) keeps secondaries lively instead of one-note.",
    "If a mix goes muddy, try the same hues with more water as separate glazes instead of one heavy puddle.",
    "Brand hexes here are planning approximations — your tube’s mass-tone may shift with brand and batch.",
  ],
  acrylic: [
    "Titanium white tints but also cools and can chalk. Add gradually and check against your ground.",
    "Mix mass-tone first, then tint/shade. Jumping straight to pastel makes matching harder later.",
    "Acrylics dry slightly darker. Plan a touch lighter than the target if matching a reference.",
    "Black quickly kills chroma. Prefer a complementary dark or Payne’s-style mix for natural shadows.",
    "Lower body / more medium turns a colour into a glaze — useful for optical layers over dry underpainting.",
    "Warm and cool versions of each primary still apply: they control whether your secondaries sing or go dull.",
    "A limited palette (split primary + earth + white) keeps mixes harmonious across a painting.",
    "Overmixing on the palette can grey colours. Leave a little variation — it reads more like paint.",
    "Golden, Liquitex, and W&N acrylics share many pigment codes — names still differ slightly by brand.",
  ],
};
